version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.17

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go mod download

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build